# Generated by Django 5.2.4 on 2025-07-17 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Amazon Web Services', max_length=100, unique=True)),
                ('logo', models.ImageField(help_text="Upload the organization's logo.", upload_to='organization_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='TechnologyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Cloud Providers', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Technology Type',
                'verbose_name_plural': 'Technology Types',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., CIS Foundation Benchmark v2.0.0', max_length=255)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.organization')),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='technology_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='api.technologytype'),
        ),
    ]
