# Generated by Django 5.2.4 on 2025-07-17 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_organization_technologytype_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='technologytype',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='organization',
            name='logo',
        ),
        migrations.AddField(
            model_name='organization',
            name='logo_upload',
            field=models.ImageField(blank=True, help_text='Upload a logo file from your system. This takes precedence over the URL.', null=True, upload_to='organization_logos/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='logo_url',
            field=models.URLField(blank=True, help_text='Or, provide a URL to an online logo image.', null=True),
        ),
    ]
