# Generated by Django 5.2.4 on 2025-07-17 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_organization_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technologytype',
            options={'ordering': ['name'], 'verbose_name': 'Technology Type', 'verbose_name_plural': 'Technology Types'},
        ),
        migrations.RemoveField(
            model_name='organization',
            name='logo_upload',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='logo_url',
        ),
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.URLField(blank=True, help_text="Paste the full URL of the organization's logo image (e.g., https://example.com/logo.png)", max_length=500, null=True),
        ),
    ]
