# Generated by Django 5.2.4 on 2025-07-17 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_userprofile_preferred_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='preferred_organization',
        ),
    ]
