# Generated by Django 5.2.4 on 2025-08-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_userprofile_preferred_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_processed',
            field=models.BooleanField(default=False, help_text='Whether the audit file has been processed'),
        ),
        migrations.AddField(
            model_name='product',
            name='processed_at',
            field=models.DateTimeField(blank=True, help_text='When processing was completed', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='processing_error',
            field=models.TextField(blank=True, help_text='Error from processing', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='processing_output',
            field=models.TextField(blank=True, help_text='Output from processing', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='processor_script',
            field=models.FileField(blank=True, help_text='Upload the Python script (audit_to_json.py) to process this audit file', null=True, upload_to='processors/'),
        ),
    ]
