# Generated by Django 5.2.4 on 2025-08-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_product_is_processed_product_processed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_processed',
        ),
        migrations.RemoveField(
            model_name='product',
            name='processed_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='processing_error',
        ),
        migrations.RemoveField(
            model_name='product',
            name='processing_output',
        ),
        migrations.RemoveField(
            model_name='product',
            name='processor_script',
        ),
        migrations.AddField(
            model_name='product',
            name='audit_json_output_path',
            field=models.CharField(blank=True, editable=False, help_text='Path to the generated JSON output from the audit file.', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='tenable_audit_file',
            field=models.FileField(blank=True, help_text='Upload the Tenable audit file. This will be processed to generate JSON data.', null=True, upload_to='tenable_audits/'),
        ),
    ]
