# Generated by Django 5.2.4 on 2025-08-06 12:47

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_organization_updated_at_product_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditParser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="A unique name for the parser, e.g., 'Google Chrome Parser'", max_length=100, unique=True)),
                ('parser_file', models.FileField(help_text='Upload the audit_parser.py file.', upload_to=api.models.get_audit_parser_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Audit Parser',
                'verbose_name_plural': 'Audit Parsers',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='audit_parser',
            field=models.ForeignKey(blank=True, help_text='Select the audit parser to process the Tenable audit file.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.auditparser'),
        ),
    ]
