# Generated by Django 5.2.4 on 2025-08-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auditparser_product_audit_parser'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='page_viewer',
            field=models.CharField(choices=[('Default', 'Default Viewer'), ('Microsoft-Edge', 'Microsoft Edge Viewer')], default='Default', help_text="Select the frontend component to use for displaying this product's details.", max_length=100),
        ),
    ]
