# Generated by Django 5.2.4 on 2025-08-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_product_page_viewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='page_viewer',
            field=models.CharField(default='Default', help_text="Select the frontend component to use for displaying this product's details.", max_length=100),
        ),
    ]
