# Generated by Django 5.2.4 on 2025-08-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='check_script',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='template',
            name='harden_script',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='template',
            name='revert_script',
            field=models.TextField(blank=True),
        ),
    ]
