# Generated by Django 5.2.4 on 2025-08-07 19:05

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_template_check_script_template_harden_script_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('Audit', 'Audit Report'), ('Harden', 'Hardening Report'), ('Revert', 'Revert Hardening Report')], max_length=10)),
                ('serial_number', models.CharField(max_length=255)),
                ('results', models.JSONField(default=list, help_text='The policy-by-policy pass/fail results.')),
                ('pdf_file', models.FileField(upload_to=api.models.get_report_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='api.template')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
