# Generated by Django 5.2.4 on 2025-08-07 20:05

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='pdf_file',
            field=models.FileField(max_length=512, upload_to=api.models.get_report_upload_path),
        ),
    ]
