# Generated by Django 5.2.4 on 2025-08-07 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_report_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('Audit-Report', 'Audit Report'), ('Hardening-Report', 'Hardening Report'), ('Revert-Hardening-Report', 'Revert Hardening Report')], max_length=50),
        ),
    ]
