# Generated by Django 5.2.4 on 2025-08-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='<Name will be generated automatically>', editable=False, help_text='e.g., CIS Foundation Benchmark v2.0.0', max_length=255),
        ),
    ]
