# Generated by Django 5.2.4 on 2025-08-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_product_page_viewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='page_viewer',
            field=models.CharField(choices=[('Default', 'Default Viewer'), ('Microsoft Edge', 'Microsoft Edge Viewer'), ('Google Chrome', 'Google Chrome Viewer'), ('Mozilla Firefox Windows', 'Mozilla Firefox Windows Viewer'), ('Windows 11', 'Windows 11 Viewer')], default='Default', help_text="Select the frontend component to use for displaying this product's details.", max_length=100),
        ),
    ]
