# Generated by Django 5.2.4 on 2025-08-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_product_page_viewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='page_viewer',
            field=models.CharField(choices=[('Default', 'Default Viewer'), ('Microsoft-Edge', 'Microsoft Edge Viewer'), ('Google-Chrome', 'Google Chrome Viewer')], default='Default', help_text="Select the frontend component to use for displaying this product's details.", max_length=100),
        ),
    ]
