# Generated by Django 5.2.4 on 2025-08-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_product_page_viewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='page_viewer',
            field=models.CharField(choices=[('Default', 'Default Viewer'), ('Microsoft Edge', 'Microsoft Edge Viewer'), ('Google Chrome', 'Google Chrome Viewer'), ('Windows 11 Standalone v3.0.0', 'Windows 11 Standalone v3.0.0 Viewer'), ('Windows 11 Standalone v4.0.0', 'Windows 11 Standalone v4.0.0 Viewer')], default='Default', help_text="Select the frontend component to use for displaying this product's details.", max_length=100),
        ),
    ]
