# Generated by Django 5.2.4 on 2025-09-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_product_page_viewer'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyScriptFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="A unique name for the script file, e.g., 'Windows 11 Standalone Scripts'", max_length=255, unique=True)),
                ('json_content', models.JSONField(help_text='The JSON content of the scripts file.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='page_viewer',
            field=models.CharField(choices=[('DefaultViewer', 'Default Viewer'), ('Microsoft Edge', 'Microsoft Edge Viewer'), ('Google Chrome', 'Google Chrome Viewer'), ('Windows 11 Standalone', 'Windows 11 Standalone Viewer'), ('Windows 11 Enterprise', 'Windows 11 Enterprise Viewer')], default='DefaultViewer', help_text="Select the frontend component to use for displaying this product's details.", max_length=100),
        ),
    ]
