# Generated by Django 5.2.4 on 2025-09-23 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_delete_policyscriptfile_alter_product_page_viewer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
            ],
            options={
                'verbose_name': 'Script',
                'verbose_name_plural': 'Add Script',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.product',),
        ),
    ]
