# Generated by Django 5.2.5 on 2025-09-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_script'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='page_viewer',
            field=models.CharField(choices=[('Default', 'Default Viewer'), ('Microsoft Edge', 'Microsoft Edge Viewer'), ('Google Chrome', 'Google Chrome Viewer'), ('Windows 11 Standalone', 'Windows 11 Standalone Viewer'), ('Windows 11 Enterprise', 'Windows 11 Enterprise Viewer'), ('Ubuntu Linux Workstation', 'Ubuntu Linux Workstation Viewer')], default='Default', help_text="Select the frontend component to use for displaying this product's details.", max_length=100),
        ),
    ]
