# Generated by Django 5.2.6 on 2025-09-29 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_alter_product_page_viewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='title',
            field=models.CharField(default='Untitled Template', max_length=255),
        ),
    ]
