# Generated by Django 5.2.6 on 2025-09-29 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_template_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='title',
        ),
    ]
