# Generated by Django 5.2.6 on 2025-09-29 22:09

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_remove_template_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='policy_files_dir',
            field=models.CharField(blank=True, editable=False, help_text='Relative path to the saved individual policy JSON files.', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='auditparser',
            name='name',
            field=models.CharField(help_text="A unique name for the parser, e.g., 'Google Chrome Parser' ", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='auditparser',
            name='parser_file',
            field=models.FileField(help_text='Upload the audit_parser.py file. ', upload_to=api.models.get_audit_parser_upload_path),
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.URLField(blank=True, help_text="Paste the full URL of the organization's logo image ", max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(help_text='e.g., Amazon Web Services ', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='audit_json_output_path',
            field=models.CharField(blank=True, editable=False, help_text='Path to the generated JSON output from the audit file. ', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='audit_parser',
            field=models.ForeignKey(blank=True, help_text='Select the audit parser to process the Tenable audit file. ', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.auditparser'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cis_benchmark_pdf',
            field=models.FileField(blank=True, help_text='Upload the CIS Benchmark PDF file ', null=True, upload_to='cis_benchmarks/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='<Name will be generated automatically>', editable=False, help_text='e.g., CIS Foundation Benchmark v2.0.0 ', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='page_viewer',
            field=models.CharField(choices=[('Default', 'Default Viewer'), ('Microsoft Edge', 'Microsoft Edge Viewer'), ('Google Chrome', 'Google Chrome Viewer'), ('Windows 11 Standalone', 'Windows 11 Standalone Viewer'), ('Windows 11 Enterprise', 'Windows 11 Enterprise Viewer'), ('Ubuntu Linux Workstation', 'Ubuntu Linux Workstation Viewer')], default='Default', help_text="Select the frontend component to use for displaying this product's details. ", max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='tenable_audit_file',
            field=models.FileField(blank=True, help_text='Upload the Tenable audit file. This will be processed to generate JSON data. ', null=True, upload_to='tenable_audits/'),
        ),
        migrations.AlterField(
            model_name='technologytype',
            name='name',
            field=models.CharField(help_text='e.g., Cloud Providers ', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.product'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='company_name',
            field=models.CharField(blank=True, help_text='Your company name ', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Upload your profile picture ', null=True, upload_to='profile_pictures/'),
        ),
    ]
