# Generated by Django 5.2.6 on 2025-10-02 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_alter_auditparser_name_alter_auditparser_parser_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontendLink',
            fields=[
            ],
            options={
                'verbose_name': 'Switch to Frontend',
                'verbose_name_plural': 'Switch to Frontend',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.product',),
        ),
    ]
