// Script to generate app icons from SVG using sharp
const fs = require('fs');
const path = require('path');
const sharp = require('sharp');

async function generateIcons() {
  const svgPath = path.join(__dirname, 'build-resources', 'icon.svg');
  const sizes = [16, 32, 48, 64, 128, 256, 512, 1024];
  
  console.log('Generating PNG icons from SVG...');
  
  try {
    // Generate PNG files for each size
    for (const size of sizes) {
      const pngPath = path.join(__dirname, 'build-resources', `icon-${size}x${size}.png`);
      
      await sharp(svgPath)
        .resize(size, size)
        .png()
        .toFile(pngPath);
      
      console.log(`✓ Generated ${size}x${size} icon`);
    }
    
    // Generate the main icon.png (256x256 for electron-builder)
    await sharp(svgPath)
      .resize(256, 256)
      .png()
      .toFile(path.join(__dirname, 'build-resources', 'icon.png'));
    
    console.log('✓ Generated icon.png (256x256)');
    console.log('\n✅ Icon generation complete!');
    console.log('\nNote: Windows .ico file will be automatically generated by electron-builder');
  } catch (error) {
    console.error('Error generating icons:', error);
    process.exit(1);
  }
}

generateIcons();
